apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  selector:
    matchLabels:
      app: demo-app
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: server
        image: go-app:2.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
